export async function sendGeminiPrompt(prompt, apiKey, contextData) {
    if (!apiKey || apiKey.trim().length === 0) {
        throw new Error("API Key missing! Please enter your Google AI Studio API Key in settings.");
    }

    const systemContext = `
You are the CS College Prep AI Mentor, a world-class Computer Science tutor helping a student prepare for college.
Current Student State:
- Study Day: Day ${contextData.currentDay} of 20
- Active Subject / Topic: ${contextData.currentDayData ? contextData.currentDayData.math.topic : 'General CS'}
- Current Level: ${contextData.levelInfo ? contextData.levelInfo.title : 'Novice'} (${contextData.xp || 0} XP)
- Completed Sessions Today: ${contextData.completedToday || 0} / 6
- Active C Playground Code Snippet:
\`\`\`c
${contextData.activeCode || '// No code written'}
\`\`\`

Give concise, encouraging, highly educational answers formatted cleanly in markdown with code blocks or formulas where applicable.
    `;

    const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${apiKey.trim()}`;

    const payload = {
        contents: [
            {
                role: "user",
                parts: [
                    { text: systemContext + "\n\nUser Question:\n" + prompt }
                ]
            }
        ]
    };

    const res = await fetch(endpoint, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload)
    });

    if (!res.ok) {
        const errorData = await res.json();
        throw new Error(errorData.error ? errorData.error.message : `API Request failed with status ${res.status}`);
    }

    const data = await res.json();
    if (data.candidates && data.candidates[0] && data.candidates[0].content) {
        return data.candidates[0].content.parts.map(p => p.text).join('\n');
    }

    throw new Error("No response content generated by Gemini.");
}
